#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jul 13 14:55:21 -04 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1bb8c60188c54130a9fab9f17c717bc5 --incr --debug typical --relax --mt 8 -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_16 -L axi_lite_ipif_v3_0_4 -L tri_mode_ethernet_mac_v9_0_16 -L xil_defaultlib -L gig_ethernet_pcs_pma_v16_2_0 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot demo_tb_behav xil_defaultlib.demo_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 1bb8c60188c54130a9fab9f17c717bc5 --incr --debug typical --relax --mt 8 -L xbip_utils_v3_0_10 -L xbip_pipe_v3_0_6 -L xbip_bram18k_v3_0_6 -L mult_gen_v12_0_16 -L axi_lite_ipif_v3_0_4 -L tri_mode_ethernet_mac_v9_0_16 -L xil_defaultlib -L gig_ethernet_pcs_pma_v16_2_0 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot demo_tb_behav xil_defaultlib.demo_tb xil_defaultlib.glbl -log elaborate.log

