set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/DAPHNE_SGMII/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.runs/synth_1/.Xil/Vivado-13382-daphne.linktest.lme/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0_in_context.xdc rfile:Vivado-13382-daphne.linktest.lme/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0/tri_mode_ethernet_mac_0_in_context.xdc id:1 order:EARLY scoped_inst:trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i} [current_design]
set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/DAPHNE_SGMII/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.runs/synth_1/.Xil/Vivado-13382-daphne.linktest.lme/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_in_context.xdc rfile:Vivado-13382-daphne.linktest.lme/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_in_context.xdc id:2 order:EARLY scoped_inst:pcs_pma} [current_design]
set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/DAPHNE_SGMII/tri_mode_ethernet_mac_0_ex/tri_mode_ethernet_mac_0_ex.runs/synth_1/.Xil/Vivado-13382-daphne.linktest.lme/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:Vivado-13382-daphne.linktest.lme/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:3 order:EARLY scoped_inst:clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/DAPHNE_SGMII/tri_mode_ethernet_mac_0_ex/imports/tri_mode_ethernet_mac_0_example_design.xdc rfile:../../../imports/tri_mode_ethernet_mac_0_example_design.xdc id:4} [current_design]
current_instance trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_i
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports {}]
current_instance
current_instance pcs_pma
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 16.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 16.000 [get_ports {}]
current_instance
current_instance clk_wiz_0
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 6.400 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 0.800 1.600} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1_p] -edges {1 2 3} -edge_shift {0.000 -0.700 -1.400} [get_ports {}]
current_instance
set_property src_info {type:XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB13 [get_ports  gtrefclk_p]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA13 [get_ports  gtrefclk_p]
set_property src_info {type:XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC10 [get_ports  txp]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD10 [get_ports  txn]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AC12 [get_ports  rxp]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD12 [get_ports  rxn]
set_property src_info {type:XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D23 [get_ports  clk_si5324_125_out_p ]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D24 [get_ports  clk_si5324_125_out_n ]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B24 [get_ports si5324_resetn]
set_property src_info {type:XDC file:4 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R17 [get_ports i2cmux_rst]
set_property src_info {type:XDC file:4 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  LOC K25 [get_ports  SDA ]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property  LOC N18 [get_ports  SCL ]
set_property src_info {type:XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M21 [get_ports  USER_CLK_P]
set_property src_info {type:XDC file:4 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M22 [get_ports  USER_CLK_N]
set_property src_info {type:XDC file:4 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M26 [get_ports linkup]
set_property src_info {type:XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T24 [get_ports  synchronization_done]
set_property src_info {type:XDC file:4 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC T25 [get_ports resetdone]
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R8 [get_ports glbl_rst]
set_property src_info {type:XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P8 [get_ports gen_tx_data]
set_property src_info {type:XDC file:4 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC R7 [get_ports chk_tx_data]
set_property src_info {type:XDC file:4 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B26 [get_ports pcie_mgt_clk_sel0]
set_property src_info {type:XDC file:4 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C24 [get_ports pcie_mgt_clk_sel1]
